<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <!-- Reference PixApiCsExt.dll from the PIX installation -->
  <ItemGroup>
    <Reference Include="PixApiCsExt">
      <HintPath>$(PixApiBinDir)\PixApiCsExt.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
